### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [Zackptg5/Searx-Android#1]
Hi,

Are you considering a FLOSS license like GNU GPL v3 for this app?

If that's the case, I think this app would have its place in [F-Droid app store](https://f-droid.org/). There is a strong, privacy focused, community behind.

You can find some documentation [here](https://f-droid.org/docs/). You can open a RFP [here](https://gitlab.com/fdroid/rfp/-/issues).

If you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by Zackptg5** [comment]
I'd be totally fine with it in f-droid. There's still some things I want to do on the app before I put it up though. Once it's out of beta phase, I'll upload it (thanks for the links btw, never put any apps up there before).

Current things on my to do list:
- Add adblock - filter list section in menu - not possible with webview
- Add multi-tab 
- Have back button work as back action
- Internationalize app
- Add tutorial
- Add search widget

I've been super busy lately so it'll likely be months before this all happens (and no I may not bother with some of them) but eventually, I'll have a non-beta release and I'll post it then

**Comment by Zackptg5** [comment]
Ok, so looking over things some more, I came to the realization that I don't have the time to learn flutter/kotlin/etc. in depth enough to implement everything I'd like above.
I'll make a few more tweaks and then submit it to fdroid. Pretty similar to how it is. Anyone is free (and encouraged) to fork and improve or make their own better app

**Comment by Zackptg5** [comment]
> Hi,
> 
> Are you considering a FLOSS license like GNU GPL v3 for this app?
> 
> If that's the case, I think this app would have its place in [F-Droid app store](https://f-droid.org/). There is a strong, privacy focused, community behind.
> 
> You can find some documentation [here](https://f-droid.org/docs/). You can open a RFP [here](https://gitlab.com/fdroid/rfp/-/issues).
> 
> If you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

Okay, released v1.0. I honestly don't see myself working on this much anymore. Added GPL3 license so if you or anybody else wants to take fork or whatever, that's completely fine with me.

Don't think I'll be able to do the fdroid submission so if you'd like to do it that's totally fine :)
